### ISSUE TITLE
JVL log list - empty / color white on white 

### ISSUE THREAD

**Issue by develeon** [rdiachenko/jlv#81]
The "JVL log list" view appears empty or font white on white background.
It seems to contain content as, as it auto-scroll to bottom and selecting lines
give different output in the "JVL log details" view.

Notably the JVL/Additional tab under Eclipse/Preference suffers from same problem.
It appears empty but actually all text is set to white font on white background?!
This is noted by selecting the editable fields Width (in Structural log table settings)
And a Foreground/Background fields in Presentational log table settings.
None of the foreground colors are set to white.  

JLV version is 1.3.3 running with 
Eclipse : Version: Neon Release (4.6.0)
Build id: 20160613-1800

**Comment by rdiachenko** [comment]
Hello @develeon, thanks for your interest. I can't promise that the issue will be fixed soon as I haven't been working on the project for a long time due to the lack of time. Any pull request is welcome.

**Comment by rdiachenko** [comment]
Fixed in https://github.com/rdiachenko/jlv/commit/865f72303546fb3720ec6b88a9ca65412cbc388d#diff-a51af5ffcea3d1c769ddeb70426d4410
